name = "wall-md"
main = "src/index.ts"
compatibility_date = "2025-02-11"
workers_dev = true

# Custom domain
routes = [
  { pattern = "wall.md", custom_domain = true },
  { pattern = "www.wall.md", custom_domain = true }
]

[assets]
directory = "public"

[[kv_namespaces]]
binding = "CLAWCON_MESSAGES"
# Fill after: wrangler kv namespace create CLAWCON_MESSAGES
id = "c6d925a8b4cf48b5b4a8bbe4c7344207"

# Optional: preview id for wrangler dev
# preview_id = "REPLACE_WITH_PREVIEW_KV_ID"
